name = "projectx-reply"
main = "src/index.js"
compatibility_date = "2025-09-27"

[env.production]
vars = { DAILY_LIMIT = "50" }
[[routes]]
pattern = "auto-reply.voidsprite.qzz.io/*"
zone_name = "voidsprite.qzz.io"
